[package]
name = "trezor-sq"
version = "0.0.1"
authors = ["Roman Zeyde <me@romanzey.de>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
fern = "0.5.6"
log = "0.4.5"
sequoia-openpgp = "0.8.0"
trezor = { git = "https://github.com/romanz/rust-trezor-api" }
subprocess = "0.1.18"
