[package]
name = "trezor-sq"
version = "0.0.1"
authors = ["Roman Zeyde <me@romanzey.de>"]
edition = "2018"

[dependencies]
clap = "2.33"
sequoia-openpgp = "0.8"
trezor = { git = "https://github.com/romanz/rust-trezor-api" }
